services:

  backend:
    container_name: backend
    build: 
      context:
        ./.docker/php
    environment:
      COMPOSER_MEMORY_LIMIT: -1
      PHP_MEMORY_LIMIT: 2GB
      CENTRIFUGO_HTTP_API_KEY: ${CENTRIFUGO_HTTP_API_KEY}
      CENTRIFUGO_TOKEN_SECRET: ${CENTRIFUGO_TOKEN_SECRET}
      CENTRIFUGO_PERSONAL_CHANNEL_PREFIX: ${CENTRIFUGO_PERSONAL_CHANNEL_PREFIX}
    volumes:
        - ./symfony:/var/www/app
    depends_on:
      - db
    networks:
      - internal
  
  db:
    container_name: db
    image: mariadb:11.4
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
    volumes:
      - ./.docker/db-data:/var/lib/mysql
    networks:
      - internal

  frontend:
    stdin_open: true
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    expose:
      - 5173
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend-http.entrypoints=web"
      - "traefik.http.routers.frontend-http.rule=PathPrefix(`/`)"
      - "traefik.http.services.frontend-http.loadbalancer.server.port=5173"
    networks:
      - internal

  nginx:
    container_name: nginx
    image: nginx:1.26.1
    volumes_from:
      - backend
    volumes:
      - ./.docker/logs/nginx:/var/log/nginx
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d/
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-http.entrypoints=web"
      - "traefik.http.routers.api-http.rule=PathPrefix(`/api`)"
      - "traefik.http.middlewares.api-http-stripprefix.stripprefix.prefixes=/api"
      - "traefik.http.routers.api-http.middlewares=api-http-stripprefix@docker"
      - "traefik.http.services.api-http.loadbalancer.server.port=80"
    networks:
      - internal

  centrifugo:
    container_name: centrifugo
    image: centrifugo/centrifugo:v5.4
    restart: unless-stopped
    environment:
      - CENTRIFUGO_API_KEY=${CENTRIFUGO_HTTP_API_KEY}
      - CENTRIFUGO_TOKEN_HMAC_SECRET_KEY=${CENTRIFUGO_TOKEN_SECRET}
      - CENTRIFUGO_LOG_LEVEL=${CENTRIFUGO_LOG_LEVEL:- "debug"}
      - CENTRIFUGO_ALLOWED_ORIGINS=${CENTRIFUGO_ALLOWED_ORIGINS:-"http://localhost http://127.0.0.1"}
      - CENTRIFUGO_NAMESPACES=${CENTRIFUGO_NAMESPACES}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.centrifugo.entrypoints=web"
      - "traefik.http.routers.centrifugo.rule=PathPrefix(`/connection/websocket`)"
      - "traefik.http.services.centrifugo.loadbalancer.server.port=8000"
    expose:
      - 8000
    depends_on:
     - db
    networks:
      - internal
  
  traefik:
    container_name: reverse-proxy
    image: traefik:v2.9
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--accesslog=true"
    ports:
      - ${APP_PORT:-80}:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - internal

networks:
      internal:

