services:

  php-smf:
    build: 
      context:
        ./.docker/php
    environment:
      COMPOSER_MEMORY_LIMIT: -1
      #XDEBUG_MODE: ${XDEBUG_MODE:-off}
      #XDEBUG_CONFIG: ${XDEBUG_CONFIG:-client_host=host.docker.internal idekey=PHPSTORM log_level=0}
      PHP_MEMORY_LIMIT: 2GB
    volumes:
        - ./symfony:/var/www/app
  
  mariadb:
    image: mariadb:lts
    environment:
      MARIADB_ROOT_PASSWORD: 4321
      MARIADB_USER: symfony
      MARIADB_PASSWORD: 4321
      MARIADB_DATABASE: symfony
    volumes:
      - ./.docker/db-data:/var/lib/mysql
  
  nginx:
    build:
      context: ./.docker/nginx
    ports:
      - ${NGINX_HOST_PORT:-80}:80
    volumes_from:
       - php-smf
    volumes:
      - ./.docker/logs/nginx:/var/log/nginx
    depends_on:
      - php-smf
      - mariadb
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: 4321

