api_controllers:
    resource:
        path: ../src/Controller/Api
        namespace: App\Controller\Api
    type: attribute
chat_controllers:
    resource:
        path: ../src/Controller/Chat
        namespace: App\Controller\Chat
    type: attribute
